esphome:
  name: koala-two-encoder
  friendly_name: Koala Two Encoder
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp8266:
  board: d1_mini

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: "mainfloor-int"
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "koala two encoder Hotspot"
    password: qwerty123

captive_portal:

# Enable logging
logger:


    
binary_sensor:
  - platform: gpio
    id: button_koala_two
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: True
    on_multi_click:
      # Double Click
      #  . Exposed as an event entity. To be used in automations inside Home Assistant
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - homeassistant.service:
            service: media_player.play_media
            data:
              entity_id: media_player.koala_two_media_player
            data_template:
              media_content_id:  https://github.com/esphome/home-assistant-voice-pe/raw/dev/sounds/center_button_double_press.flac
              media_content_type: MUSIC
        - logger.log: "send double click sound"
        #needed to ensure sound is played before event starts:
        - delay: 2s
        - event.trigger:
            id: encoder_button_press_event
            event_type: "double_press"
      # press and hold
      #  . Exposed as an event entity. To be used in automations inside Home Assistant
    - timing:
      - ON for at least 1s
      then:

        - homeassistant.service:
            service: media_player.play_media
            data:
              entity_id: media_player.koala_two_media_player
            data_template:
              media_content_id:  https://github.com/esphome/home-assistant-voice-pe/raw/dev/sounds/center_button_long_press.flac
              media_content_type: MUSIC
        - logger.log: "send long press sound"
        #needed to ensure sound is played before event starts:
        - delay: 2s
        - event.trigger:
            id: encoder_button_press_event
            event_type: "long_press"
    - timing:

      # single click
      #  . Exposed as an event entity. To be used in automations inside Home Assistant
      - ON for at most .49s
      - OFF for at least 0.25s
      then:
#        - homeassistant.service:
#            service: media_player.media_play_pause
#            data:
#              entity_id: media_player.koala_two_media_player_2
#        - logger.log: "single click - play/pause"
        - homeassistant.service:
            service: media_player.play_media
            data:
              entity_id: media_player.koala_two_media_player
            data_template:
              media_content_id:  https://github.com/esphome/home-assistant-voice-pe/raw/dev/sounds/center_button_press.flac
              media_content_type: MUSIC
        - logger.log: "send single click sound"
        #needed to ensure sound is played before event starts:
        - delay: 2s
        - event.trigger:
            id: encoder_button_press_event
            event_type: "single_press"
    - timing:
      # triple click
      #  . Exposed as an event entity. To be used in automations inside Home Assistant
      - ON for at most 1s
      - OFF for at most 0.25s
      - ON for at most 1s
      - OFF for at most 0.25s
      - ON for at most 1s
      - OFF for at least 0.25s
      then:
#        - homeassistant.service:
#            service: media_player.media_play_pause
#            data:
#              entity_id: media_player.koala_two_media_player_2
 #       - logger.log: "triple click - play/pause"
        - homeassistant.service:
            service: media_player.play_media
            data:
              entity_id: media_player.koala_two_media_player
            data_template:
              media_content_id:  https://github.com/esphome/home-assistant-voice-pe/raw/dev/sounds/center_button_triple_press.flac
              media_content_type: MUSIC
        - logger.log: "send triple click sound"
        #needed to ensure sound is played before event starts:
        - delay: 2s
        - event.trigger:
            id: encoder_button_press_event
            event_type: "triple_press"
sensor:
  - platform: rotary_encoder
    id: knob_koala_two
    pin_a: 4
    pin_b: 5

    on_clockwise:
      - homeassistant.service:
          service: media_player.volume_set
          data_template:
            entity_id: media_player.koala_two_media_player
            volume_level: "{{ state_attr('media_player.koala_two_media_player', 'volume_level') + 0.05 }}"
      - logger.log: "volume up"
    on_anticlockwise:
      - homeassistant.service:
          service: media_player.volume_set
          data_template:
            entity_id: media_player.koala_two_media_player
            volume_level: "{{ state_attr('media_player.koala_two_media_player', 'volume_level') - 0.05 }}"
      - logger.log: "volume down"
event:
  # Event entity exposed to the user to automate on complex center button presses.
  # The simple press is not exposed as it is used to control the device itself.
  - platform: template
    id: encoder_button_press_event
    name: "Button press"
    icon: mdi:button-pointer
    device_class: button
    event_types:
      - double_press
      - triple_press
      - long_press 
      - single_press             
script:
  - id: volume_up
    then:
      - homeassistant.service:
          service: media_player.volume_up
          data:
            entity_id: media_player.koala_two_media_player
      - logger.log: "vol up trigger"
      - sensor.rotary_encoder.set_value:
          id: knob_koala_two
          value: 0
  - id: volume_down
    then:
      - homeassistant.service:
          service: media_player.volume_down
          data:
            entity_id: media_player.koala_two_media_player
      - logger.log: "vol down trigger"
      - sensor.rotary_encoder.set_value:
          id: knob_koala_two
          value: 0
 
